#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=1.11.0
PACKAGE=samtools
TOOL=$PACKAGE
DIRECTORY=/opt/packages/$PACKAGE/$VERSION
LANG=C

singularity exec -B /ocean $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"