#!/bin/bash

module load singularity/3.5.3

VERSION=1.11.0
PACKAGE=samtools
TOOL=$PACKAGE
DIRECTORY=/opt/packages/samtools/$VERSION
LANG=C

singularity exec -B /pylon5 $DIRECTORY/singularity-$PACKAGE-$VERSION.simg $TOOL "$@"
