#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=1.10.0
PACKAGE=samtools
TOOL=$PACKAGE
DIRECTORY=/opt/packages/samtools/$VERSION
LANG=C

singularity exec -B /pylon5 $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
